### ISSUE TITLE
Customizing Editor Questions

### ISSUE THREAD

**Issue by 99bits** [SN-RECIT-formation-a-distance/moodle-atto_reciteditor#6]
Thank you so much for this incredible editor.  
Makes working with layout in Moodle so much easier.  

I have some questions regarding customizing the editor.
1.  How to change the colors of the dotted lines of the boxes.
2.  How to make my own templates and template showcase.

Merci Beaucoup

**Comment by gustavobazzo** [comment]
Hello 99bits,

Thank you again for your comment.

Here are the answers:

1. The colors of the dotted lines are not customizable in any user setting. To do this, you will need to fork the project and modify it in the CSS code.
2. In the new version, users will be able to save their own templates. (or you can have your own showcase [https://github.com/SN-RECIT-formation-a-distance/html-bootstrap-editor-showcase](https://github.com/SN-RECIT-formation-a-distance/html-bootstrap-editor-showcase)
